services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - '3001:3000'
        tty: true
        # command: pnpm start
